kakao:
  content-type: application/x-www-form-urlencoded
  iss: https://kauth.kakao.com
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  login-redirect-uri: ${LOGIN_REDIRECT_URI}
  logout-redirect-uri: ${LOGOUT_REDIRECT_URI}

spring:
  application:
    name: horong
  mail:
    host: ${GMAIL_HOST}
    port: ${GMAIL_PORT}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
    auth-code-expiration-millis: 1800000

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      cluster:
        max-redirects: 6
        nodes: ${REDIS_NODES}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-wait: 20000
  elasticsearch:
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    uris: ${ELASTICSEARCH_URIS}

  graphql:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:*}
      allowed-methods: ${ALLOWED_METHODS:*}
      allowed-headers: ${ALLOWED_HEADERS:Origin,Access-Control-Allow-Origin}
      exposed-headers: ${EXPOSED_HEADERS:Authorization,Content-Type}
      allow-credentials: ${ALLOWED_CREDENTIALS:true}
      one-hour: 3600
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: ${SECRET_KEY}
  access-token-exp: ${ACCESS_TOKEN_EXP}
  refresh-token-exp: ${REFRESH_TOKEN_EXP}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static-region: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

coolsms:
  api-key: ${COOLSMS_APIKEY}
  api-secret: ${COOLSMS_APISECRET}
  from-number: ${COOLSMS_FROMNUMBER}

WebClient:
  url: ${WEBCLIENT_URL}