spring:
  config:
    activate:
      on-profile: dev
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
    open-in-view: true

logging:
  level:
    org:
      springframework:
        web: debug
    ssafy:
      horong: debug

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
    path: '/docs'
  swagger-ui:
    enabled: true
    path: '/swagger'
    try-it-out-enabled: true
    operations-sorter: alpha

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
